Traceback (most recent call last):
  File "/home/dcp/data-store/profiling/profile_bundles.py", line 75, in <module>
    resp = patch_bundle(c, uuid, version)
  File "/home/dcp/data-store/profiling/profile_bundles.py", line 53, in patch_bundle
    add_files=files,
  File "/home/dcp/.virtualenvs/dcp/lib/python3.6/site-packages/hca/util/__init__.py", line 202, in __call__
    return self._consume_response(self._request(kwargs))
  File "/home/dcp/.virtualenvs/dcp/lib/python3.6/site-packages/hca/util/__init__.py", line 190, in _request
    raise SwaggerAPIException(response=res)
hca.util.exceptions.SwaggerAPIException: timed_out: Timed out processing request. (HTTP 504). Details:
{"code": "timed_out", "status": 504, "title": "Timed out processing request.", "traces": {"140127661713152": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 519, in set_result\n    waiter.add_result(self)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 79, in add_result\n    with self.lock:\n"], "140127670105856": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 521, in set_result\n    self._invoke_callbacks()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 81, in add_result\n    self.event.set()\n"], "140127888185088": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/task/chalicelib/dss/api/bundles/__init__.py\", line 287, in _get_file_metadata\n    return json.loads(file_metadata)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 26, in wrapped\n    return meth(*args, **kwargs)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 219, in get\n    return response['Body'].read()\n", "  File \"/var/task/botocore/response.py\", line 88, in read\n    return chunk\n", "  File \"/var/task/urllib3/response.py\", line 471, in read\n    return data\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 468, in read\n    return s\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 617, in _safe_read\n    return b\"\".join(s)\n", "  File \"/var/lang/lib/python3.6/socket.py\", line 586, in readinto\n    return self._sock.recv_into(b)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 1012, in recv_into\n    return self.read(nbytes, buffer)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 874, in read\n    return self._sslobj.read(len, buffer)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 634, in read\n    return v\n"], "140127896577792": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/task/chalicelib/dss/api/bundles/__init__.py\", line 287, in _get_file_metadata\n    return json.loads(file_metadata)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 26, in wrapped\n    return meth(*args, **kwargs)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 219, in get\n    return response['Body'].read()\n", "  File \"/var/task/botocore/response.py\", line 88, in read\n    return chunk\n", "  File \"/var/task/urllib3/response.py\", line 471, in read\n    return data\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 468, in read\n    return s\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 617, in _safe_read\n    return b\"\".join(s)\n", "  File \"/var/lang/lib/python3.6/socket.py\", line 586, in readinto\n    return self._sock.recv_into(b)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 1012, in recv_into\n    return self.read(nbytes, buffer)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 874, in read\n    return self._sslobj.read(len, buffer)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 634, in read\n    return v\n"], "140127904970496": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/task/chalicelib/dss/api/bundles/__init__.py\", line 287, in _get_file_metadata\n    return json.loads(file_metadata)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 26, in wrapped\n    return meth(*args, **kwargs)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 219, in get\n    return response['Body'].read()\n", "  File \"/var/task/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/task/botocore/client.py\", line 663, in _make_api_call\n    return parsed_response\n", "  File \"/var/task/botocore/client.py\", line 667, in _make_request\n    return self._endpoint.make_request(operation_model, request_dict)\n", "  File \"/var/task/botocore/endpoint.py\", line 102, in make_request\n    return self._send_request(request_dict, operation_model)\n", "  File \"/var/task/botocore/endpoint.py\", line 158, in _send_request\n    return success_response\n", "  File \"/var/task/botocore/endpoint.py\", line 183, in _get_response\n    return success_response, exception\n", "  File \"/var/task/botocore/endpoint.py\", line 220, in _do_get_response\n    return (http_response, parsed_response), None\n", "  File \"/var/task/botocore/endpoint.py\", line 244, in _send\n    return self.http_session.send(request)\n", "  File \"/var/task/botocore/httpsession.py\", line 274, in send\n    return http_response\n", "  File \"/var/task/urllib3/connectionpool.py\", line 733, in urlopen\n    return response\n", "  File \"/var/task/urllib3/connectionpool.py\", line 402, in _make_request\n    return httplib_response\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 1345, in getresponse\n    return response\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 368, in begin\n    self.will_close = True\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 288, in _read_status\n    return version, status, reason\n", "  File \"/var/lang/lib/python3.6/socket.py\", line 586, in readinto\n    return self._sock.recv_into(b)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 1012, in recv_into\n    return self.read(nbytes, buffer)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 874, in read\n    return self._sslobj.read(len, buffer)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 634, in read\n    return v\n"], "140127913363200": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/task/chalicelib/dss/api/bundles/__init__.py\", line 287, in _get_file_metadata\n    return json.loads(file_metadata)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 26, in wrapped\n    return meth(*args, **kwargs)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 219, in get\n    return response['Body'].read()\n", "  File \"/var/task/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/task/botocore/client.py\", line 663, in _make_api_call\n    return parsed_response\n", "  File \"/var/task/botocore/client.py\", line 667, in _make_request\n    return self._endpoint.make_request(operation_model, request_dict)\n", "  File \"/var/task/botocore/endpoint.py\", line 102, in make_request\n    return self._send_request(request_dict, operation_model)\n", "  File \"/var/task/botocore/endpoint.py\", line 158, in _send_request\n    return success_response\n", "  File \"/var/task/botocore/endpoint.py\", line 183, in _get_response\n    return success_response, exception\n", "  File \"/var/task/botocore/endpoint.py\", line 220, in _do_get_response\n    return (http_response, parsed_response), None\n", "  File \"/var/task/botocore/endpoint.py\", line 244, in _send\n    return self.http_session.send(request)\n", "  File \"/var/task/botocore/httpsession.py\", line 274, in send\n    return http_response\n", "  File \"/var/task/urllib3/connectionpool.py\", line 733, in urlopen\n    return response\n", "  File \"/var/task/urllib3/connectionpool.py\", line 402, in _make_request\n    return httplib_response\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 1345, in getresponse\n    return response\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 368, in begin\n    self.will_close = True\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 288, in _read_status\n    return version, status, reason\n", "  File \"/var/lang/lib/python3.6/socket.py\", line 586, in readinto\n    return self._sock.recv_into(b)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 1012, in recv_into\n    return self.read(nbytes, buffer)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 874, in read\n    return self._sslobj.read(len, buffer)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 634, in read\n    return v\n"], "140127921755904": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/task/chalicelib/dss/api/bundles/__init__.py\", line 287, in _get_file_metadata\n    return json.loads(file_metadata)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 26, in wrapped\n    return meth(*args, **kwargs)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 219, in get\n    return response['Body'].read()\n", "  File \"/var/task/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/task/botocore/client.py\", line 663, in _make_api_call\n    return parsed_response\n", "  File \"/var/task/botocore/client.py\", line 667, in _make_request\n    return self._endpoint.make_request(operation_model, request_dict)\n", "  File \"/var/task/botocore/endpoint.py\", line 102, in make_request\n    return self._send_request(request_dict, operation_model)\n", "  File \"/var/task/botocore/endpoint.py\", line 158, in _send_request\n    return success_response\n", "  File \"/var/task/botocore/endpoint.py\", line 183, in _get_response\n    return success_response, exception\n", "  File \"/var/task/botocore/endpoint.py\", line 220, in _do_get_response\n    return (http_response, parsed_response), None\n", "  File \"/var/task/botocore/endpoint.py\", line 244, in _send\n    return self.http_session.send(request)\n", "  File \"/var/task/botocore/httpsession.py\", line 274, in send\n    return http_response\n", "  File \"/var/task/urllib3/connectionpool.py\", line 733, in urlopen\n    return response\n", "  File \"/var/task/urllib3/connectionpool.py\", line 402, in _make_request\n    return httplib_response\n"], "140127930148608": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 521, in set_result\n    self._invoke_callbacks()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 81, in add_result\n    self.event.set()\n"], "140127938541312": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/task/chalicelib/dss/api/bundles/__init__.py\", line 287, in _get_file_metadata\n    return json.loads(file_metadata)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 26, in wrapped\n    return meth(*args, **kwargs)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 219, in get\n    return response['Body'].read()\n", "  File \"/var/task/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/task/botocore/client.py\", line 663, in _make_api_call\n    return parsed_response\n", "  File \"/var/task/botocore/client.py\", line 667, in _make_request\n    return self._endpoint.make_request(operation_model, request_dict)\n", "  File \"/var/task/botocore/endpoint.py\", line 102, in make_request\n    return self._send_request(request_dict, operation_model)\n", "  File \"/var/task/botocore/endpoint.py\", line 158, in _send_request\n    return success_response\n", "  File \"/var/task/botocore/endpoint.py\", line 183, in _get_response\n    return success_response, exception\n", "  File \"/var/task/botocore/endpoint.py\", line 220, in _do_get_response\n    return (http_response, parsed_response), None\n", "  File \"/var/task/botocore/endpoint.py\", line 244, in _send\n    return self.http_session.send(request)\n", "  File \"/var/task/botocore/httpsession.py\", line 274, in send\n    return http_response\n", "  File \"/var/task/urllib3/connectionpool.py\", line 733, in urlopen\n    return response\n", "  File \"/var/task/urllib3/connectionpool.py\", line 402, in _make_request\n    return httplib_response\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 1345, in getresponse\n    return response\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 368, in begin\n    self.will_close = True\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 288, in _read_status\n    return version, status, reason\n", "  File \"/var/lang/lib/python3.6/socket.py\", line 586, in readinto\n    return self._sock.recv_into(b)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 1012, in recv_into\n    return self.read(nbytes, buffer)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 874, in read\n    return self._sslobj.read(len, buffer)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 634, in read\n    return v\n"], "140128425056000": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/task/chalicelib/dss/api/bundles/__init__.py\", line 287, in _get_file_metadata\n    return json.loads(file_metadata)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 26, in wrapped\n    return meth(*args, **kwargs)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 219, in get\n    return response['Body'].read()\n", "  File \"/var/task/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/task/botocore/client.py\", line 663, in _make_api_call\n    return parsed_response\n", "  File \"/var/task/botocore/client.py\", line 667, in _make_request\n    return self._endpoint.make_request(operation_model, request_dict)\n", "  File \"/var/task/botocore/endpoint.py\", line 102, in make_request\n    return self._send_request(request_dict, operation_model)\n", "  File \"/var/task/botocore/endpoint.py\", line 158, in _send_request\n    return success_response\n", "  File \"/var/task/botocore/endpoint.py\", line 183, in _get_response\n    return success_response, exception\n", "  File \"/var/task/botocore/endpoint.py\", line 220, in _do_get_response\n    return (http_response, parsed_response), None\n", "  File \"/var/task/botocore/endpoint.py\", line 244, in _send\n    return self.http_session.send(request)\n", "  File \"/var/task/botocore/httpsession.py\", line 274, in send\n    return http_response\n", "  File \"/var/task/urllib3/connectionpool.py\", line 733, in urlopen\n    return response\n", "  File \"/var/task/urllib3/connectionpool.py\", line 402, in _make_request\n    return httplib_response\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 1345, in getresponse\n    return response\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 368, in begin\n    self.will_close = True\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 288, in _read_status\n    return version, status, reason\n", "  File \"/var/lang/lib/python3.6/socket.py\", line 586, in readinto\n    return self._sock.recv_into(b)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 1012, in recv_into\n    return self.read(nbytes, buffer)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 874, in read\n    return self._sslobj.read(len, buffer)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 634, in read\n    return v\n"], "140128433448704": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/task/chalicelib/dss/api/bundles/__init__.py\", line 287, in _get_file_metadata\n    return json.loads(file_metadata)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 26, in wrapped\n    return meth(*args, **kwargs)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 219, in get\n    return response['Body'].read()\n", "  File \"/var/task/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/task/botocore/client.py\", line 663, in _make_api_call\n    return parsed_response\n", "  File \"/var/task/botocore/client.py\", line 667, in _make_request\n    return self._endpoint.make_request(operation_model, request_dict)\n", "  File \"/var/task/botocore/endpoint.py\", line 102, in make_request\n    return self._send_request(request_dict, operation_model)\n", "  File \"/var/task/botocore/endpoint.py\", line 158, in _send_request\n    return success_response\n", "  File \"/var/task/botocore/endpoint.py\", line 183, in _get_response\n    return success_response, exception\n", "  File \"/var/task/botocore/endpoint.py\", line 220, in _do_get_response\n    return (http_response, parsed_response), None\n", "  File \"/var/task/botocore/endpoint.py\", line 244, in _send\n    return self.http_session.send(request)\n", "  File \"/var/task/botocore/httpsession.py\", line 274, in send\n    return http_response\n", "  File \"/var/task/urllib3/connectionpool.py\", line 733, in urlopen\n    return response\n", "  File \"/var/task/urllib3/connectionpool.py\", line 402, in _make_request\n    return httplib_response\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 1345, in getresponse\n    return response\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 368, in begin\n    self.will_close = True\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 288, in _read_status\n    return version, status, reason\n", "  File \"/var/lang/lib/python3.6/socket.py\", line 586, in readinto\n    return self._sock.recv_into(b)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 1012, in recv_into\n    return self.read(nbytes, buffer)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 874, in read\n    return self._sslobj.read(len, buffer)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 634, in read\n    return v\n"], "140128441841408": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/task/chalicelib/dss/api/bundles/__init__.py\", line 287, in _get_file_metadata\n    return json.loads(file_metadata)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 26, in wrapped\n    return meth(*args, **kwargs)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 219, in get\n    return response['Body'].read()\n", "  File \"/var/task/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/task/botocore/client.py\", line 663, in _make_api_call\n    return parsed_response\n", "  File \"/var/task/botocore/client.py\", line 667, in _make_request\n    return self._endpoint.make_request(operation_model, request_dict)\n", "  File \"/var/task/botocore/endpoint.py\", line 102, in make_request\n    return self._send_request(request_dict, operation_model)\n", "  File \"/var/task/botocore/endpoint.py\", line 158, in _send_request\n    return success_response\n", "  File \"/var/task/botocore/endpoint.py\", line 183, in _get_response\n    return success_response, exception\n", "  File \"/var/task/botocore/endpoint.py\", line 220, in _do_get_response\n    return (http_response, parsed_response), None\n", "  File \"/var/task/botocore/endpoint.py\", line 244, in _send\n    return self.http_session.send(request)\n", "  File \"/var/task/botocore/httpsession.py\", line 274, in send\n    return http_response\n", "  File \"/var/task/urllib3/connectionpool.py\", line 733, in urlopen\n    return response\n", "  File \"/var/task/urllib3/connectionpool.py\", line 402, in _make_request\n    return httplib_response\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 1239, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n", "  File \"/var/task/botocore/awsrequest.py\", line 127, in _send_request\n    return rval\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 1285, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 1234, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n", "  File \"/var/task/botocore/awsrequest.py\", line 176, in _send_output\n    self.send(message_body)\n", "  File \"/var/task/botocore/awsrequest.py\", line 236, in send\n    return super(AWSConnection, self).send(str)\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 993, in send\n    \"or an iterable, got %r\" % type(data))\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 978, in sendall\n    return socket.sendall(self, data, flags)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 944, in send\n    return self._sslobj.write(data)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 642, in write\n    return self._sslobj.write(data)\n"], "140128450234112": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 521, in set_result\n    self._invoke_callbacks()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 81, in add_result\n    self.event.set()\n"], "140128458626816": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 521, in set_result\n    self._invoke_callbacks()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 81, in add_result\n    self.event.set()\n"], "140128467019520": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 521, in set_result\n    self._invoke_callbacks()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 81, in add_result\n    self.event.set()\n"], "140128475412224": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/task/chalicelib/dss/api/bundles/__init__.py\", line 287, in _get_file_metadata\n    return json.loads(file_metadata)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 26, in wrapped\n    return meth(*args, **kwargs)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 219, in get\n    return response['Body'].read()\n", "  File \"/var/task/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/task/botocore/client.py\", line 663, in _make_api_call\n    return parsed_response\n", "  File \"/var/task/botocore/client.py\", line 667, in _make_request\n    return self._endpoint.make_request(operation_model, request_dict)\n", "  File \"/var/task/botocore/endpoint.py\", line 102, in make_request\n    return self._send_request(request_dict, operation_model)\n", "  File \"/var/task/botocore/endpoint.py\", line 158, in _send_request\n    return success_response\n", "  File \"/var/task/botocore/endpoint.py\", line 183, in _get_response\n    return success_response, exception\n", "  File \"/var/task/botocore/endpoint.py\", line 220, in _do_get_response\n    return (http_response, parsed_response), None\n", "  File \"/var/task/botocore/endpoint.py\", line 244, in _send\n    return self.http_session.send(request)\n", "  File \"/var/task/botocore/httpsession.py\", line 274, in send\n    return http_response\n", "  File \"/var/task/urllib3/connectionpool.py\", line 733, in urlopen\n    return response\n", "  File \"/var/task/urllib3/connectionpool.py\", line 402, in _make_request\n    return httplib_response\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 1345, in getresponse\n    return response\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 368, in begin\n    self.will_close = True\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 288, in _read_status\n    return version, status, reason\n", "  File \"/var/lang/lib/python3.6/socket.py\", line 586, in readinto\n    return self._sock.recv_into(b)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 1012, in recv_into\n    return self.read(nbytes, buffer)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 874, in read\n    return self._sslobj.read(len, buffer)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 634, in read\n    return v\n"], "140128820381440": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 521, in set_result\n    self._invoke_callbacks()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 81, in add_result\n    self.event.set()\n"], "140128829036288": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/task/chalicelib/dss/api/bundles/__init__.py\", line 287, in _get_file_metadata\n    return json.loads(file_metadata)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 26, in wrapped\n    return meth(*args, **kwargs)\n", "  File \"/var/task/cloud_blobstore/s3.py\", line 219, in get\n    return response['Body'].read()\n", "  File \"/var/task/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/task/botocore/client.py\", line 663, in _make_api_call\n    return parsed_response\n", "  File \"/var/task/botocore/client.py\", line 667, in _make_request\n    return self._endpoint.make_request(operation_model, request_dict)\n", "  File \"/var/task/botocore/endpoint.py\", line 102, in make_request\n    return self._send_request(request_dict, operation_model)\n", "  File \"/var/task/botocore/endpoint.py\", line 158, in _send_request\n    return success_response\n", "  File \"/var/task/botocore/endpoint.py\", line 183, in _get_response\n    return success_response, exception\n", "  File \"/var/task/botocore/endpoint.py\", line 220, in _do_get_response\n    return (http_response, parsed_response), None\n", "  File \"/var/task/botocore/endpoint.py\", line 244, in _send\n    return self.http_session.send(request)\n", "  File \"/var/task/botocore/httpsession.py\", line 274, in send\n    return http_response\n", "  File \"/var/task/urllib3/connectionpool.py\", line 733, in urlopen\n    return response\n", "  File \"/var/task/urllib3/connectionpool.py\", line 402, in _make_request\n    return httplib_response\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 1239, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n", "  File \"/var/task/botocore/awsrequest.py\", line 127, in _send_request\n    return rval\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 1285, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 1234, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n", "  File \"/var/task/botocore/awsrequest.py\", line 176, in _send_output\n    self.send(message_body)\n", "  File \"/var/task/botocore/awsrequest.py\", line 236, in send\n    return super(AWSConnection, self).send(str)\n", "  File \"/var/lang/lib/python3.6/http/client.py\", line 993, in send\n    \"or an iterable, got %r\" % type(data))\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 978, in sendall\n    return socket.sendall(self, data, flags)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 944, in send\n    return self._sslobj.write(data)\n", "  File \"/var/lang/lib/python3.6/ssl.py\", line 642, in write\n    return self._sslobj.write(data)\n"], "140128837428992": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 521, in set_result\n    self._invoke_callbacks()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 81, in add_result\n    self.event.set()\n"], "140128845821696": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 62, in run\n    self.future.set_result(result)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 521, in set_result\n    self._invoke_callbacks()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 81, in add_result\n    self.event.set()\n"], "140128859002624": ["  File \"/var/lang/lib/python3.6/threading.py\", line 884, in _bootstrap\n    self._bootstrap_inner()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n    self.run()\n", "  File \"/var/lang/lib/python3.6/threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n    work_item.run()\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/thread.py\", line 56, in run\n    result = self.fn(*self.args, **self.kwargs)\n", "  File \"/var/task/app.py\", line 185, in dispatch\n    flask_res = flask_app.full_dispatch_request()\n", "  File \"/var/task/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n", "  File \"/var/task/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n", "  File \"/var/task/connexion/decorators/decorator.py\", line 73, in wrapper\n    response = function(request)\n", "  File \"/var/task/connexion/decorators/security.py\", line 122, in wrapper\n    return function(request)\n", "  File \"/var/task/connexion/decorators/uri_parsing.py\", line 117, in wrapper\n    response = function(request)\n", "  File \"/var/task/chalicelib/dss/__init__.py\", line 155, in wrapper\n    return origwrapper(request)\n", "  File \"/var/task/connexion/decorators/validation.py\", line 163, in wrapper\n    response = function(request)\n", "  File \"/var/task/chalicelib/dss/__init__.py\", line 111, in wrapper\n    return origwrapper(request)\n", "  File \"/var/task/connexion/decorators/validation.py\", line 336, in wrapper\n    return function(request)\n", "  File \"/var/task/connexion/decorators/response.py\", line 104, in wrapper\n    response = function(request)\n", "  File \"/var/task/connexion/decorators/decorator.py\", line 44, in wrapper\n    response = function(request)\n", "  File \"/var/task/connexion/decorators/parameter.py\", line 207, in wrapper\n    return function(**kwargs)\n", "  File \"/var/task/chalicelib/dss/error.py\", line 59, in wrapper\n    return func(*args, **kwargs)\n", "  File \"/var/task/chalicelib/dss/util/security.py\", line 113, in wrapper\n    return func(*args, **kwargs)\n", "  File \"/var/task/chalicelib/dss/api/bundles/__init__.py\", line 215, in patch\n    bundle['files'].extend(build_bundle_file_metadata(Replica[replica], add_files))\n", "  File \"/var/task/chalicelib/dss/api/bundles/__init__.py\", line 293, in build_bundle_file_metadata\n    for future in as_completed(futures):\n", "  File \"/var/lang/lib/python3.6/concurrent/futures/_base.py\", line 242, in as_completed\n    with waiter.lock:\n"]}}
